//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGen v{{GENERATOR_VERSION}}
//     Script: generate-code.bat (or generate-code.sh for Unix)
//     Timestamp: {{GENERATED_AT}}
//     Template: {{TEMPLATE_NAME}}
//     Target: {{RESULT_TYPE}} ({{TARGET_FRAMEWORK}})
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     regenerated. Consider modifying the template instead.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.Runtime.CompilerServices;
using ZeroResult.Errors;

namespace ZeroResult;

public {{Modifier}} partial struct {{ResultType}}<T, TError>
    where TError : IError
{
{{AdditionalFragments/AsyncOperations.template.cs}}
}
