//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGen v{{GENERATOR_VERSION}}
//     Script: generate-code.bat (or generate-code.sh for Unix)
//     Timestamp: {{GENERATED_AT}}
//     Template: {{TEMPLATE_NAME}}
//     Target: {{RESULT_TYPE}} ({{TARGET_FRAMEWORK}})
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     regenerated. Consider modifying the template instead.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using ZeroResult.Errors;

namespace ZeroResult;

public {{Modifier}} partial struct {{ResultType}}<T, TError>
    where TError : IError
{
    /// <summary>
    /// Implicitly converts a value to a successful <see cref="{{ResultType}}{T, TError}"/>.
    /// </summary>
    /// <param name="value">The success value to convert</param>
    [SuppressMessage("Design", "CA2225:Operator overloads have named alternates",
        Justification = "Explicit alternatives exist via {{ResultType}}.Success/Failure factory methods. " +
                        "Implicit conversion is safe for error types implementing IError and " +
                        "maintains symmetry with success case conversions.")]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator {{ResultType}}<T, TError>(T value)
        => new(value);

    /// <summary>
    /// Implicitly converts an error to a failed <see cref="{{ResultType}}{T, TError}"/>.
    /// </summary>
    /// <param name="error">The error to convert</param>
    [SuppressMessage("Design", "CA2225:Operator overloads have named alternates",
        Justification = "Explicit alternatives exist via {{ResultType}}.Success/Failure factory methods. " +
                        "Implicit conversion is safe for error types implementing IError and " +
                        "maintains symmetry with success case conversions.")]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator {{ResultType}}<T, TError>(TError error)
        => new(error);
}
