//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGen v1.0.0-beta+fd92bf6d4ede0e60812d222d946282a14ec88fd5
//     Script: generate-code.bat (or generate-code.sh for Unix)
//     Timestamp: 6/16/2025 6:33:21 PM
//     Template: Conversions.template.cs
//     Target: StackResult (net8.0+)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     regenerated. Consider modifying the template instead.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using ZeroResult.Errors;

namespace ZeroResult;

public readonly ref partial struct StackResult<T, TError>
    where TError : IError
{
    /// <summary>
    /// Implicitly converts a value to a successful <see cref="StackResult{T, TError}"/>.
    /// </summary>
    /// <param name="value">The success value to convert</param>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator StackResult<T, TError>(T value)
        => new(value);

    /// <summary>
    /// Implicitly converts an error to a failed <see cref="StackResult{T, TError}"/>.
    /// </summary>
    /// <param name="error">The error to convert</param>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator StackResult<T, TError>(TError error)
        => new(error);

    /// <summary>
    /// Converts the current <see cref="StackResult{T, TError}"/> to <see cref="HeapResult{T, TError}"/>.
    /// </summary>
    /// <returns>
    /// A new <see cref="HeapResult{T, TError}"/> with the same success/failure state.
    /// </returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public HeapResult<T, TError> AsHeapResult() 
        => IsSuccess 
            ? new HeapResult<T, TError>(_value) 
            : new HeapResult<T, TError>(_error);
}
