//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGen v1.0.0-beta+4ec844e718a39d1268da49e731d19e6ed2a3b569
//     Script: generate-code.bat (or generate-code.sh for Unix)
//     Timestamp: 6/15/2025 8:40:42 PM
//     Template: Conversions.template.cs
//     Target: StackResult (net8.0+)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     regenerated. Consider modifying the template instead.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using ZeroResult.Errors;

namespace ZeroResult;

public readonly ref partial struct StackResult<T, TError>
    where TError : IError
{
    /// <summary>
    /// Implicitly converts a value to a successful <see cref="StackResult{T, TError}"/>.
    /// </summary>
    /// <param name="value">The success value to convert</param>
    [SuppressMessage("Design", "CA2225:Operator overloads have named alternates",
        Justification = "Explicit alternatives exist via StackResult.Success/Failure factory methods. " +
                        "Implicit conversion is safe for error types implementing IError and " +
                        "maintains symmetry with success case conversions.")]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator StackResult<T, TError>(T value)
        => new(value);

    /// <summary>
    /// Implicitly converts an error to a failed <see cref="StackResult{T, TError}"/>.
    /// </summary>
    /// <param name="error">The error to convert</param>
    [SuppressMessage("Design", "CA2225:Operator overloads have named alternates",
        Justification = "Explicit alternatives exist via StackResult.Success/Failure factory methods. " +
                        "Implicit conversion is safe for error types implementing IError and " +
                        "maintains symmetry with success case conversions.")]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator StackResult<T, TError>(TError error)
        => new(error);
}
