//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGen v1.0.0-beta+2aba22e929803a296ead64d46c51322a032541ff
//     Script: generate-code.bat (or generate-code.sh for Unix)
//     Timestamp: 6/21/2025 1:35:02 PM
//     Template: Conversions.template.cs
//     Target: StackResult (net8.0+)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     regenerated. Consider modifying the template instead.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using ZeroResult.Errors;

namespace ZeroResult;

public readonly ref partial struct StackResult<T, TError>
    where TError : IError
{
    /// <summary>
    /// Implicitly converts a value to a successful <see cref="StackResult{T, TError}"/>.
    /// </summary>
    /// <param name="value">The success value to convert</param>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator StackResult<T, TError>(T value)
        => new(value);

    /// <summary>
    /// Implicitly converts an error to a failed <see cref="StackResult{T, TError}"/>.
    /// </summary>
    /// <param name="error">The error to convert</param>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator StackResult<T, TError>(TError error)
        => new(error);

    /// <summary>
    /// Converts the current <see cref="StackResult{T, TError}"/> to <see cref="Result{T, TError}"/>.
    /// </summary>
    /// <returns>
    /// A new <see cref="Result{T, TError}"/> with the same success/failure state.
    /// </returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Result<T, TError> AsResult() 
        => IsSuccess 
            ? new Result<T, TError>(_value) 
            : new Result<T, TError>(_error);
}
