//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGen v1.0.0-beta+2aba22e929803a296ead64d46c51322a032541ff
//     Script: generate-code.bat (or generate-code.sh for Unix)
//     Timestamp: 6/21/2025 1:35:02 PM
//     Template: CreateOperations.template.cs
//     Target: StackResult (net8.0+)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     regenerated. Consider modifying the template instead.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using ZeroResult.Errors;

namespace ZeroResult;

/// <summary>
/// Provides factory methods for creating <see cref="StackResult{T, TError}"/> instances.
/// Designed for zero-allocation result creation in high-performance scenarios.
/// </summary>
public static partial class StackResult
{
    /// <summary>
    /// Creates a successful <see cref="StackResult{T, TError}"/> with the specified value.
    /// </summary>
    /// <typeparam name="T">The type of the successful result value</typeparam>
    /// <typeparam name="TError">The error type implementing <see cref="IError"/></typeparam>
    /// <param name="value">The value to return on success</param>
    /// <returns>A successful result containing the value</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static StackResult<T, TError> Success<T, TError>(T value)
        where TError: IError
        => new(value);

    /// <summary>
    /// Creates a failed <see cref="StackResult{T, TError}"/> with the specified error.
    /// </summary>
    /// <typeparam name="T">The expected value type when successful</typeparam>
    /// <typeparam name="TError">The error type implementing <see cref="IError"/></typeparam>
    /// <param name="error">The error that caused the failure</param>
    /// <returns>A failed result containing the error</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static StackResult<T, TError> Failure<T, TError>(TError error)
        where TError: IError
        => new(error);
}
