//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGen v1.0.0-beta+fd92bf6d4ede0e60812d222d946282a14ec88fd5
//     Script: generate-code.bat (or generate-code.sh for Unix)
//     Timestamp: 6/16/2025 6:33:22 PM
//     Template: Conversions.template.cs
//     Target: HeapResult (net8.0+)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     regenerated. Consider modifying the template instead.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using ZeroResult.Errors;

namespace ZeroResult;

public readonly partial struct HeapResult<T, TError>
    where TError : IError
{
    /// <summary>
    /// Implicitly converts a value to a successful <see cref="HeapResult{T, TError}"/>.
    /// </summary>
    /// <param name="value">The success value to convert</param>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator HeapResult<T, TError>(T value)
        => new(value);

    /// <summary>
    /// Implicitly converts an error to a failed <see cref="HeapResult{T, TError}"/>.
    /// </summary>
    /// <param name="error">The error to convert</param>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator HeapResult<T, TError>(TError error)
        => new(error);

    /// <summary>
    /// Implicitly converts a <see cref="HeapResult{T, TError}"/> to a completed <see cref="ValueTask"/> of <see cref="HeapResult{T, TError}"/>.
    /// </summary>
    /// <param name="result">The result to convert</param>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ValueTask<HeapResult<T, TError>>(HeapResult<T, TError> result)
        => new(result);

    /// <summary>
    /// Converts the current <see cref="HeapResult{T, TError}"/> to <see cref="StackResult{T, TError}"/>.
    /// </summary>
    /// <returns>
    /// A new <see cref="StackResult{T, TError}"/> with the same success/failure state.
    /// </returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public StackResult<T, TError> AsStackResult() 
        => IsSuccess 
            ? new StackResult<T, TError>(_value) 
            : new StackResult<T, TError>(_error);
}
